### ISSUE TITLE
Missing Ng2SelectModule and Ng2Select duplicated on index.js 

### ISSUE THREAD

**Issue by leocaseiro** [Gbuomprisco/ng2-material-select#11]
Hi @Gbuomprisco,

As I mentioned in #4, I'm having some issues in my editor with the declaration type and I believe that's the reason @maryamsoprano is having issues with SystemJS(I'm not sure btw).

The newest version `ng2-material-select@0.0.9` it's coming with a duplicated `Ng2Select` instead of the `Ng2SelectModule` on `./index.js` generated by webpack, so my editor complains about the `NgModule`.

> index.js
> 
> ``` javascript
> "use strict";
> const Ng2Select = require('./dist/ng2-select.bundle.js').Ng2Select;
> exports.Ng2Select = Ng2Select;
> exports.Ng2Select = Ng2Select;
> //# sourceMappingURL=index.js.map
> ```
## 

> Editor (phpstorm/webstorm)
> <img width="471" alt="screen shot 2016-09-30 at 11 32 18 am" src="https://cloud.githubusercontent.com/assets/940070/18977919/ee6b93a6-8701-11e6-87f0-84534637a33b.png">

**Comment by Gbuomprisco** [comment]
Hi @leocaseiro, I updated the library. Does that still happen to you? Thanks!

**Comment by leocaseiro** [comment]
Hi @Gbuomprisco, thank you so much for doing that!

The version `ng2-material-select@0.1.0` is working perfectly and the declaration is good.

Hope help others too.
