### ISSUE TITLE
Uncaught Error: Unexpected value 'undefined' declared by the module 'AppModule'

### ISSUE THREAD

**Issue by aderbas** [Gbuomprisco/ng2-material-select#17]
I try to use `ng2-material-select` in my project. I'm using angular-cli. Intalled by npm `npm install ng2-material-select --save` and configure in my project

```
import { Ng2SelectModule }      from 'ng2-material-select';
import { Ng2Select }            from 'ng2-material-select';

@NgModule({
  declarations: [
      ....,
      Ng2Select
  ],
  imports: [
     ....,
    Ng2SelectModule
  ]
 ...
})
```

Before run `ng serve` gets this error: `Uncaught Error: Unexpected value 'undefined' declared by the module 'AppModule'`. if I remove Ng2 for declarations and imports, project back works.

**Comment by aderbas** [comment]
Angular 2 does not use more `directives: [...]` on `Component({ ... })` as shown in the documentation

**Comment by Gbuomprisco** [comment]
True, it's out of date right now! :) Hope this is solved

**Comment by Hiblton** [comment]
Gbuomprisco hi, so how i have to declare it for actual Angular version?
