### ISSUE TITLE
If ng2-material-select is used in a form, clicking on it will submit the form

### ISSUE THREAD

**Issue by musahaidari** [Gbuomprisco/ng2-material-select#18]
When `ng2-material-select` package is used inside a form, clicking on the dropdown generated by `ng2-select` tag submits the form. 

This issue actually is originated from a dependency module `ng2-material-dropdown`, that is solved by a pull request (that can be found [here ](https://github.com/Gbuomprisco/ng2-material-dropdown/pull/5)) already, however it is not reflected here in this package when installed using npm,

**My assumption/ suggestion**: I tried to clone the repo from github, and built it manually and I could see the issue was fixed, so I guess the solution is to update the npm repo with a new build with latest version of `ng2-material-dropdown`

**A quick look at the issue from ng2-material-dropdown**: Inside its `template.html` file:

```
<button class='ng2-dropdown-button' (click)="toggleMenu()">
```

In this piece of code `type="button"` should have been added,

**Comment by Gbuomprisco** [comment]
Hi @musahaidari, are you using the latest version? :) A user submitted a PR and I merged it :)

**Comment by musahaidari** [comment]
Hi. Yes. I am using the latest versions from npm. The problem is that if I use the npm version it is still problematic, but if I clone the github repo and build with webpack the "type" property appears i.e. issue is removed.

**Comment by Gbuomprisco** [comment]
I see, it seems the 2 versions are different. I'll try to publish again to npm :)

**Comment by musahaidari** [comment]
Hi. Yes. I am using the latest version of ng2-material-dropdown ( and the
ng2-material-selelct) and I can see the change in ng2-material-dropdown
package. But the build version of this package does not have this change.
Even I mentioned this issue on that PR too.

**Comment by musahaidari** [comment]
Hi @Gbuomprisco!

Have you got time on this? Actually we are using your plugin to build 3 web portals, and your fix will help us alot.

Thank you.

**Comment by Gbuomprisco** [comment]
Hi @musahaidari,

I published a new version that should have the latest improvements of ng2-material-dropdown. Can you try again? Thanks!

**Comment by musahaidari** [comment]
Hi @Gbuomprisco ,

Thank you for the efforts taken. 
However I think there should be some problem somewhere, since I still cannot see the `type="button"` in the new version of this package. 

Before this update, the version was 0.1.1 and now it is 0.1.2, but still the same issue exists. Following is my console: 

```
G:\js\my-project>npm install --save ng2-material-select
my-project@1.0.0 G:\js\my-project
`-- ng2-material-select@0.1.2
  +-- equals@1.0.5
  | `-- jkroso-type@1.1.1
  `-- ng2-material-dropdown@0.3.9
```

And this is the line 906 to 913 of the `ng2-select.bundle.js` (out of which only line 910 is of interest):

```
/***/ },
/* 10 */
/***/ function(module, exports) {

    module.exports = "<button class='ng2-dropdown-button' (click)=\"toggleMenu()\">\n    <ng-content></ng-content>\n\n    <span class=\"caret\" [hidden]=\"!showCaret\"></span>\n</button>\n";

/***/ },
/* 11 */
```

So what do you think would be the problem here?

**Comment by namatullah** [comment]
Hello @Gbuomprisco.

If you can spare time on this subject it would help me and my team too, since we are also facing the same issue.

Thank you in advance.

**Comment by musahaidari** [comment]
Hi @Gbuomprisco!

We are sorry to keep bothering you. Just wanted to ask if you got the chance to have a look into this case again.

Thank you for your efforts and the patience.

**Comment by Gbuomprisco** [comment]
Hi @musahaidari and @namatullah,

I pushed another version. I tried it in my package and I see type=button in the button. Can you try again please? Can you also make sure you delete ng2-material-dropdown and ng2-material-select from the node_modules folders first? Thanks!

**Comment by musahaidari** [comment]
Hi @Gbuomprisco ,

I verified your new submit has fixed this issue and it works as expected. I need to again appreciate the time you have spent to write and maintain this wonderful project.

**Comment by Gbuomprisco** [comment]
Happy it solved it :)
