### ISSUE TITLE
update to RC5/6

### ISSUE THREAD

**Issue by pasqLisena** [Gbuomprisco/ng2-material-select#2]
Can you please make also this package compatible with Angular's version RC5? Or directly RC6 (I have seen [this other issue](https://github.com/Gbuomprisco/ng2-tag-input/issues/49).

Thank you in advance! 😄

**Comment by Gbuomprisco** [comment]
Hey @pasqLisena,

Will probably look at it this weekend :)

Thanks for reporting

**Comment by Gbuomprisco** [comment]
Hey @pasqLisena,

I just published a version integrated with rc6. Please let me know if it works, I haven't had the time to verify.

Thanks a lot!

**Comment by oharbo** [comment]
I've got this error: 
ng2-select.bundle.js:474 Uncaught TypeError: Cannot read property 'Output' of undefined

**Comment by Gbuomprisco** [comment]
Hi @garbo-a.

Is this happening with the new version? would be useful to see the package.json :)

**Comment by oharbo** [comment]
Hi @Gbuomprisco, yes that happened with the latest version with rc6 integration. I tried to use your  ng2-material-select with latest https://github.com/mgechev/angular2-seed/ (no other external modules)
Sorry, I reset package.json, will try to add your package a bit later =)

**Comment by oharbo** [comment]
Here is my package.json 
[package.json.zip](https://github.com/Gbuomprisco/ng2-material-select/files/456620/package.json.zip)

**Comment by Gbuomprisco** [comment]
HI @garbo-a, I'll have a look at this. In the meantime there is another release that should fix other things.
