### ISSUE TITLE
How to import Ng2SelectModule?

### ISSUE THREAD

**Issue by leocaseiro** [Gbuomprisco/ng2-material-select#4]
Hi @Gbuomprisco,

Thank you for this directive.

I'm trying to import the `Ng2SelectModule`, but I'm not sure what is the correct path.

I've tried these ways and none worked:

``` typescript
import { Ng2SelectModule } from 'ng2-material-select';
import { Ng2SelectModule } from 'ng2-material-select/dist/src/ng2-select.module';
```

PS: If I import only the directive `Ng2Select` as your example. It asks for the `ng2-dropdown-button`;

``` bash
Template parse errors:
'ng2-dropdown-button' is not a known element:
1. If 'ng2-dropdown-button' is an Angular component, then verify that it is part of this module.
2. If 'ng2-dropdown-button' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("<ng2-dropdown>
    [ERROR ->]<ng2-dropdown-button>
        {{ placeholderDisplay }}
    </ng2-dropdown-button>
"): Ng2Select@1:4
```

The far I've got was:

``` typescript
import { Ng2Select } from 'ng2-material-select';
import { Ng2DropdownModule } from 'ng2-material-dropdown';

@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        Ng2DropdownModule,
      ...
    ],
    declarations: [
        Ng2Select
    ]
})
```

However, I'm still trying to fix some issues.

**Comment by Gbuomprisco** [comment]
Hi @leocaseiro!

I would try this:

```
import { BrowserModule } from '@angular/platform-browser';
import { Ng2SelectModule } from 'ng2-material-select';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { Ng2SelectModule } from 'ng2-material-select';

@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        ReactiveFormsModule,
        Ng2SelectModule
    ]
})
export class YourModule {}
platformBrowserDynamic().bootstrapModule(YourModule)
```

If it still does not work, then there it is a problem. Let me know! Please see https://github.com/Gbuomprisco/ng2-material-select/blob/master/demo/app.ts as reference

**Comment by leocaseiro** [comment]
Hi @Gbuomprisco, thanks for your quick reply.

Unfortunatelly, I'm having the same issue: 

``` javascript
error TS2305: Module '"/node_modules/ng2-material-select/index"' has no exported member 'Ng2SelectModule'.
```

I believe we need to import Ng2SelectModule into [ng2-select.ts](https://github.com/Gbuomprisco/ng2-material-select/blob/master/src/ng2-select.ts) which becomes the `./ng2-select.bundle.js`.

At the moment, I just have access to `Ng2Select`.

**Comment by leocaseiro** [comment]
Would you mind trying download from npm and check if the files are ok?

I've installed the 0.0.6:

```
npm install --save ng2-material-select@0.0.6
```

**Comment by Gbuomprisco** [comment]
Hi @leocaseiro, I merged your stuff, version 0.0.7. Hopefully works!

**Comment by leocaseiro** [comment]
Hi @Gbuomprisco, thanks for that!

It's working now. However, there's a file called `typings.bundle.d.ts` that confuses my editor(webstorm). So, my autocomplete doesn't work in import.

<img width="559" alt="screen shot 2016-09-20 at 8 03 39 pm" src="https://cloud.githubusercontent.com/assets/940070/18666124/7fb86ba0-7f6d-11e6-91ab-5a9068ab0e8c.png">

I deleted this file from `node_modules/ng2-material-select/dist/typings.bundle.d.ts` and now it works fine the autocomplete as well.

Perhaps will be fixed when #3 is done.

**Comment by maryamsoprano** [comment]
Hi, would you mind describe how can load this component? I added it into module.ts and systemConfig.js like the others, but I get following error:

> "(SystemJS) XHR error (404 Not Found) loading http://localhost:3002/ng2-material-select   patchProperty/desc.set/wrapFn@http://localhost:3002/node_modules/zone.js/dist/zone.js:647:26    ZoneDelegate.prototype.invokeTask@http://localhost:3002/node_modules/zone.js/dist/zone.js:236:23    Zone.prototype.runTask@http://localhost:3002/node_modules/zone.js/dist/zone.js:136:28   ZoneTask/this.invoke@http://localhost:3002/node_modules/zone.js/dist/zone.js:304:28     Error loading http://localhost:3002/ng2-material-select as "ng2-material-select" from http://localhost:3002/app/module.js"

I added it into module.ts:
`import { Ng2SelectModule } from 'ng2-material-select';
import { Ng2Select } from 'ng2-material-select';
@NgModule({
  imports: [
....
       Ng2SelectModule],
 exports: [

```
Ng2SelectModule
```

  ],
 declarations: [
 ...
    Ng2Select
]
`

and also in systemjs.config:

`var map = {'Ng2Select': '/node_modules/ng2-material-select'},
  var packages = {    'Ng2Select': { defaultExtension: 'js' },
`

I would be very appreciate if describe me how can solve this error.I did everything which I've done for other components.also I use typescript (version2) angular(final version) and ng2-select-material(version 0.0.7)

Many thanks

**Comment by leocaseiro** [comment]
HI @maryamsoprano, you won't need Ng2Select, remove it and it'll work.

Only import the `Ng2SelectModule`.

In regards to SystemJS, I don't think you need to add, I'm not sure, I use webpack instead.

**Comment by maryamsoprano** [comment]
Hi, 
Thanks for your response. 
I tried that, but still same error

Regards, 
Maryam

**Comment by leocaseiro** [comment]
I'm sorry to hear that.
What version are you using? I'm on `0.0.7`.

**Comment by maryamsoprano** [comment]
Ng-Material-select version is 0.0.7
tsc -v  is Version 2.1.0-dev.20160921
node version is v6.2.2
angular version is  "version": "2.0.0"

**Comment by maryamsoprano** [comment]
module.ts:

```
import { NgModule, ApplicationRef, ModuleWithProviders } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { HttpModule, Http } from '@angular/http';
import { FormsModule } from '@angular/forms';
import { Routes, RouterModule } from '@angular/router'// import { PLATFORM_DIRECTIVES, PLATFORM_PIPES, provide, enableProdMode } from '@angular/core';
import {   enableProdMode } from '@angular/core';
import { XHRBackend } from "@angular/http";
import { InMemoryBackendService, SEED_DATA } from 'angular2-in-memory-web-api';
import { Ng2SelectModule } from 'ng2-material-select';
//import { Ng2Select } from 'ng2-material-select';
@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    Ng2SelectModule,
    //   Ng2Select,
    OverlayModule.forRoot(),
    RouterModule,
    routing
    ],
  exports: [
     //   Ng2SelectModule,
    //  Ng2Select
  ],
  providers: [
    appRoutingProviders,
    ConfigService,
    LogService,
    AuthenticationService,
    ContactsService,
    FileService,
  ],
  declarations: [
     // Ng2Select,
    // Ng2Select,
    createTemplateRenderer("item", "index"),
    //MdToolbar,
    Ng2SelectModule,
  ],
  entryComponents: [
     App
  ],
  bootstrap: [ App]
})
  }
```

systemconfig.js:

```
`(function (global) {
  // map tells the System loader where to look for things
  var map = {
    'app': '/app', // 'dist',
    '@angular': '/node_modules/@angular',
    'angular2-in-memory-web-api': '/node_modules/angular2-in-memory-web-api',
    'rxjs': '/node_modules/rxjs',
    'reflect-metadata': '/node_modules/reflect-metadata',
    '@angular2-material': '/node_modules/@angular2-material',
    //   'Ng2Select': '/node_modules/ng2-material-select',
    'Ng2SelectModule': '/node_modules/ng2-material-select',
    //  'ng2-material-select': '/node_modules/ng2-material-select',
      'moment': '/node_modules/moment',
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app': { main: 'main.js', defaultExtension: 'js' },
    'rxjs': { defaultExtension: 'js' },
    'reflect-metadata': { defaultExtension: 'js' },
    'Ng2SelectModule': { main: 'index', defaultExtension: 'js' },
    //  'ng2-material-select': { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
    'moment': { main: 'moment.js', defaultExtension: 'js' },
   };
  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'forms',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'upgrade'
  ];

  function packIndex(pkgName) {
    packages['@angular/' + pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }
  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/' + pkgName] = { main: 'bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
  };
  // Most environments should use UMD; some (Karma) need the individual index files
  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);
  var config = {
    map: map,
    packages: packages
  }
  System.config(config);
})(this);

```

error is:

> (SystemJS) XHR error (404 Not Found) loading http://localhost:3002/ng2-material-select
>     patchProperty/desc.set/wrapFn@http://localhost:3002/node_modules/zone.js/dist/zone.js:647:26
>     ZoneDelegate.prototype.invokeTask@http://localhost:3002/node_modules/zone.js/dist/zone.js:236:23
>     Zone.prototype.runTask@http://localhost:3002/node_modules/zone.js/dist/zone.js:136:28
>     ZoneTask/this.invoke@http://localhost:3002/node_modules/zone.js/dist/zone.js:304:28

```
Error loading http://localhost:3002/ng2-material-select as "ng2-material-select" from http://localhost:3002/app/module.js
```

I am very confused about that, what is wrong in configuration? 
thanks

`

**Comment by maryamsoprano** [comment]
Hi all,
after upgrading into newer version,still have problem in loading ng2-material-select. Do you have any advice and idea about systemjs.config?

thanks

**Comment by leocaseiro** [comment]
Hi @maryamsoprano, have you tried using webpack?
Even the angular cli now uses webpack.

I'm sorry, I don't use SystemJS.

PS: I think the error is with declaration types. I'll open an issue with that.
