### ISSUE TITLE
Cannot find name 'require'

### ISSUE THREAD

**Issue by maryamsoprano** [Gbuomprisco/ng2-material-select#5]
Hi,

After importing ng2select by following up everything written in the examples. I get loading error 

> Error loading http://localhost:3002/ng2-material-select as "ng2-material-select" from http://localhost:3002/app/lib/components/app/app.js

 also during compilation I get error : Cannot find name 'require'

in my app.ts:

```
import { Component, ViewEncapsulation, OnInit, Input, forwardRef } from '@angular/core';
import { MdIcon, MdIconRegistry } from '@angular2-material/icon';
import { NG_VALUE_ACCESSOR, ControlValueAccessor } from '@angular/forms';
import { Ng2Select } from 'ng2-material-select';



@Component({
    selector: 'app',
    templateUrl: './app/lib/components/myApp/app.html',
    inputs: ['items', 'sid', 'value', 'disabled'],
    directives: [
        MdIcon,
        Ng2Select,

    ],

    viewProviders: [MdIconRegistry]
})
```

and in the systemjs.config.js:
I added   'Ng2Select': '/node_modules/ng2-material-select', into the map and also  'Ng2Select': { main: 'index.js', defaultExtension: 'js' }, in pacakges.

would you please give me any advice about this problem?

Thanks in advance.

**Comment by Gbuomprisco** [comment]
Hi @maryamsoprano, it looks like you're using the configuration for a previous version of Angular. The current version for this component requires the latest Angular (and soon Typescript). See the demo for instance :)

**Comment by maryamsoprano** [comment]
Hi,
I updated my angular and typescript now. Also after updating I had to move all directives in whole ts files into @Ngmodule.
But still same error. 
in ng-material-selet\index.ts:

> error: cannot find name require

and when I start the project , in my browser webconsole:

> Error loading http://192.168.0.46:3002/ng2-material-select as "ng2-material-select" from http://192.168.0.46:3002/app/module.js

version of typescript:
$tsc -v : Version 2.0,2 

version of angularjs:
version :2.0.0
(I updated angular by npm )

I need your urgent help.

Many thanks

**Comment by maryamsoprano** [comment]
My application does not start with webpack. Does it cause the mentioned error?
Also I can't use template:require(''./app/lib/components/myCom/chkbox.html'') because it gets me typescript error:cannot find name 'require'

**Comment by maryamsoprano** [comment]
The whole error while I run application is:

> (SystemJS) XHR error (404 Not Found) loading http://localhost:3002/ng2-material-select
>     patchProperty/desc.set/wrapFn@http://localhost:3002/node_modules/zone.js/dist/zone.js:647:26
>     ZoneDelegate.prototype.invokeTask@http://localhost:3002/node_modules/zone.js/dist/zone.js:236:23
>     Zone.prototype.runTask@http://localhost:3002/node_modules/zone.js/dist/zone.js:136:28
>     ZoneTask/this.invoke@http://localhost:3002/node_modules/zone.js/dist/zone.js:304:28

```
Error loading http://localhost:3002/ng2-material-select as "ng2-material-select" from http://localhost:3002/app/module.js
```

and this is my tsconfig.json file:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "types": [
      "node"
    ],
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts",
    "typings"
  ]
}
```

I could not find a way to solve this.please help me

**Comment by maryamsoprano** [comment]
when I ran your demo project, following error is raised:
[0] ../typings/globals/node/index.d.ts(384,11): error TS2430: Interface 'NodeBuffer' incorrectly extends interface 'Uint8Array'.
[0]   Types of property 'fill' are incompatible.
[0]     Type '(value: any, offset?: number, end?: number) => Buffer' is not assignable to type '(value: number, start?: number, end?: number) => this'.
[0]       Type 'Buffer' is not assignable to type 'this'.

**Comment by Gbuomprisco** [comment]
Hi @maryamsoprano, I'll have a look soon, but for now:
- don't exclude "typings" in your tsconfig
- try setting target to es6

**Comment by maryamsoprano** [comment]
thanks for your response. I changed es5 into es6, but there are lots of error and conflicts that I should fix them now.
I also added node and jasmine into typings.json and upgrade typing's version into 1.3.3.

typings.json:

```
{
  "ambientDependencies": {
    "es6-shim": "github:DefinitelyTyped/DefinitelyTyped/es6-shim/es6-shim.d.ts#7de6c3dd94feaeb21f20054b9f30d5dabc5efabd"
  },
  "globalDependencies": {
    "core-js": "registry:dt/core-js#0.0.0+20160317120654",
    "hammerjs": "registry:dt/hammerjs#2.0.8+20160724063812",
    "jasmine": "registry:dt/jasmine",
    "node": "registry:env/node#6.0.0+20160918225031"
  }
}
```

Although I have va require:NodeRequire in ng2-material-select/typings/globals/node/index.d.ts, it is undefined in ng2-material-select/index.ts.

thanks for your consideration.

**Comment by Gbuomprisco** [comment]
I am moving away from typings in the next release, it should avoid this sort of errors hopefully. DId you manage to run the project somehow?

**Comment by maryamsoprano** [comment]
The demo project runs but does not show anything (just Loading...)
in console of FireFox I have 

> GET http://localhost:3002/ [HTTP/1.1 200 OK 54ms]
> GET http://localhost:3002/home/home.css [HTTP/1.1 200 OK 76ms]
> GET http://localhost:3002/polyfills.bundle.js [HTTP/1.1 200 OK 14ms]
> GET http://localhost:3002/vendor.bundle.js [HTTP/1.1 200 OK 14ms]
> GET http://localhost:3002/app.bundle.js [HTTP/1.1 200 OK 147ms]
> Expected ':' but found '20px'.  Declaration dropped. home.css:6:16
> SyntaxError: let is a reserved identifier app.bundle.js:103:1
> GET XHR 
> http://localhost:3002/sockjs-node/info [HTTP/1.1 200 OK 6ms]
> GET http://localhost:3002/sockjs-node/764/f552fc0p/websocket

And in  my own project .it has loading error (with systemjs.config):
(SystemJS) XHR error (404 Not Found) loading

I tries to map it like other components, but still has error
 var map = {'ng2-material-select': 'node_modules/ng2-material-select',}
var package = { 'ng2-material-select': {main: 'index.js' , defaultExtension: 'js' },}

and in module just import { Ng2SelectModule } from 'ng2-material-select'; and import this module into @NgModule

**Comment by Gbuomprisco** [comment]
Probably the main file is at `./dist/index.js`. Could you create a minimal repository with your configuration so that I can run and try to adjust it?

**Comment by maryamsoprano** [comment]
Thanks for your response . I 've created a new repository in following path with systemjs,config and module. I spent more than 3 hours to load this directives, but still have loading (404) error.

https://github.com/maryamsoprano/ng2-material-select-test

thanks in advance.

**Comment by Gbuomprisco** [comment]
HI @maryamsoprano. Have a look at https://github.com/Gbuomprisco/ng2-material-select-test.

I pushed changes to make it work. I got to say I think if you are using the same configuration you may want to change a little bit, cause I had to install some packages and move things around to make it work. Maybe look at some systemjs boilerplates (or better, move to webpack) :)

**Comment by maryamsoprano** [comment]
Many many thanks for your help and consideration. you actually save me and
my time. :)

I think there are 2 things in this directive that  need to improve, Please
correct me if I am wrong.

First:

If in the demo project  the number of options increase , this component
would not show anything:
I tested with this number of items:
options = ['Angular', 'React', 'Angular', 'React', 'Angular', 'React',
'Angular', 'React', 'Angular', 'React', 'Angular', 'React']

second:
 if I use it inside other custom directive, it's list goes behind that
directive.

Regards

Maryam Gharibi

JAVA PROGRAMMER

T: +61 2 9900 2200 <+61299002200>

SOPRANO DESIGN

Priority mobile messaging for enterprise.

Winner: Appsters
https://www.sopranodesign.com/soprano-gamma-wins-appsters-award-best-enterprise-app-europe/?utm_source=EmailSig&utm_medium=email&utm_campaign=newsig
 | APICTA
https://www.sopranodesign.com/soprano-design-recognised-for-best-communication-technology-in-asia-pacific-by-winning-prestigious-2014-apicta-award-for-soprano-gamma/?utm_source=EmailSig&utm_medium=email&utm_campaign=newsig
 | iAwards
https://www.sopranodesign.com/soprano-gamma-recognised-top-enterprise-messaging-product-australia/?utm_source=EmailSig&utm_medium=email&utm_campaign=newsig
 | Export
https://www.sopranodesign.com/soprano-recognised-for-innovation-with-australian-export-award/?utm_source=Emailsig&utm_medium=email&utm_campaign=newsig
[image: Logo]
https://www.sopranodesign.com/?utm_source=EmailSig&utm_medium=email&utm_campaign=newsig
 [image: TWT]
https://twitter.com/Soprano_Design?utm_source=EmailSig&utm_medium=email&utm_campaign=newsig[image:
LI]
https://www.linkedin.com/company/soprano-design?utm_source=EmailSig&utm_medium=email&utm_campaign=newsig[image:
FB]
https://goo.gl/EliA4G?utm_source=EmailSig&utm_medium=email&utm_campaign=newsig[image:
YT]
https://www.youtube.com/user/SopranoDesign?utm_source=EmailSig&utm_medium=email&utm_campaign=newsig[image:
RSS]
https://www.sopranodesign.com/feed/?utm_source=EmailSig&utm_medium=email&utm_campaign=newsig
