### ISSUE TITLE
Feature: Hightlight selected item in blue

### ISSUE THREAD

**Issue by leocaseiro** [Gbuomprisco/ng2-material-select#8]
Hi @Gbuomprisco,

I can see the selected item with the background gray color, however, if you mouse out you'll loose the selected item. In the material angular 1, they selected the item in blue.

What do you think about doing the same?

Demo: https://material.angularjs.org/latest/demo/select

![screen shot 2016-09-21 at 10 24 17 am](https://cloud.githubusercontent.com/assets/940070/18693528/acf8ccb8-7fe5-11e6-811e-f1c66af40bb6.png)

**Comment by Gbuomprisco** [comment]
Hey @leocaseiro, yeah good catch 👍

**Comment by Gbuomprisco** [comment]
Hi @leocaseiro, the new version should have that improvement :)

**Comment by leocaseiro** [comment]
Hi @Gbuomprisco, thanks for that. Looks awesome! Loved it!
